---
geometry: margin=1in
fontsize: 12pt
colorlinks: True
csl: config/chicago-in-text-shortened-author-title.csl
link-citations: True
linkcolor: blue
toccolor: black
toc: True
secnumdepth: 3
include-auto: True
author: Ian Cornelius
---
