name: Deploy active syllabi

on:
  push:
    branches: main
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Working directory check
        run: |
          pwd
          ls

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install XeLaTeX
        run: sudo apt-get install -y texlive-xetex

      - name: Verify dependencies
        run: |
          pandoc --version
          xetex --version

      - name: Build
        run: bash build-pdf.sh

      - name: Check for Resulting PDF
        run: |
          ls build/*.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*.pdf
